remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: Systeem en Regeltechniek Modules
description: Theory support for educational purposes for Systeem en Regeltechniek at TU Delft.
